apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tokenmesh-data
  namespace: tokenmesh
spec:
  storageClassName: ebs-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
