apiVersion: v1
kind: Service
metadata:
  name: tokenmesh-web
  namespace: tokenmesh
  labels:
    app: tokenmesh-web
spec:
  type: LoadBalancer
  selector:
    app: tokenmesh-web
  ports:
    - name: http
      port: 80
      targetPort: http
